geonames_api: "http://34.105.131.180:8000/locations?"
url_api: "http://34.105.131.180:2322/api?"
url_reverse: "http://34.105.131.180:2322/reverse?"
lang: "en"
osm_keys:
  - "place"
blacklist:
  - "america"
  - "south america"
  - "north america"
  - "asia"
  - "antartida"
  - "europe"
  - "africa"
  - "oceania"
  - "west"
  - "east"
  - "south"
  - "east"
  - "mom"
  - "dmem"
  - "birds"
  - "eu"
  - "medicine"
  - "jaguar"
  - "mom"
  - "dad"
  - "fitz"

