name: Open PRs in sample-creation and outbreak-detection
on:
  release:
    types: [created]
  
jobs:
  open_outbreak_detection_pr:
    runs-on: ubuntu-latest
    steps:
      - name: open PR at outbreak-detection
        run: |
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_USER_NAME }}
          git config --global user.password ${{secrets.GH_API_TOKEN}}
          git clone https://${{secrets.GH_USER_NAME}}:${{secrets.GH_API_TOKEN}}@github.com/lifebit-ai/nlp-outbreak-detection.git && cd nlp-outbreak-detection
          git switch -c geocoder/${GITHUB_REF##*/}
          sed -i -r "s/nlp-geocode-module\.git@v*.*.*/nlp-geocode-module\.git\@${GITHUB_REF##*/}/" "requirements.txt"
          git add requirements.txt
          git commit -m "Updates geocoder version to ${GITHUB_REF##*/}"
          git push --set-upstream origin geocoder/${GITHUB_REF##*/}
          gh pr create --title "Update geocoder version to ${GITHUB_REF##*/}" --body "It updates geocoder version to ${GITHUB_REF##*/}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
  open_sample_creation_pr:
    runs-on: ubuntu-latest
    steps:
      - name: open PR at sample-creation
        run: |
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_USER_NAME }}
          git config --global user.password ${{secrets.GH_API_TOKEN}}
          git clone https://${{secrets.GH_USER_NAME}}:${{secrets.GH_API_TOKEN}}@github.com/lifebit-ai/nlp-sample-creation.git && cd nlp-sample-creation
          git switch -c geocoder/${GITHUB_REF##*/}
          sed -i -r "s/nlp-geocode-module\.git@v*.*.*/nlp-geocode-module\.git\@${GITHUB_REF##*/}/" "requirements.txt"
          git add requirements.txt
          git commit -m "Updates geocoder version to ${GITHUB_REF##*/}"
          git push --set-upstream origin geocoder/${GITHUB_REF##*/}
          gh pr create --title "Update geocoder version to ${GITHUB_REF##*/}" --body "It updates geocoder version to ${GITHUB_REF##*/}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
