on:
  release:
    types: [published]
  
jobs:
  open_sample_creation_pr:
    runs-on: ubuntu-latest
    steps:
      - name: install GH
        run: |
          apt-get install wget
          wget https://github.com/cli/cli/releases/download/v2.13.0/gh_2.13.0_linux_amd64.tar.gz
          tar -zxvf gh_2.13.0_linux_amd64.tar.gz
          chmod +x gh_2.13.0_linux_amd64/bin/gh
          cp gh_2.13.0_linux_amd64/bin/gh /bin

      - name: open PR at sample-creation
        run: |
          echo ${{ secrets.GH_API_TOKEN }} | gh auth login --with-token
          gh repo clone lifebit-ai/nlp-sample-creation && cd nlp-sample-creation
          git switch -c geocoder/${GITHUB_REF##*/}
          git push https://${{ secrets.GH_USER_NAME }}:${{ secrets.GH_API_TOKEN }}}@github.com/lifebit-ai/nlp-sample-creation.git --set-upstream origin geocoder/${GITHUB_REF##*/}
          gh pr create --title "Update geocoder version" --body "Please update geocoder version"'
  open_outbreak_detection_pr:
    runs-on: ubuntu-latest
    steps:
      - name: install GH
        run: |
          apt-get install wget
          wget https://github.com/cli/cli/releases/download/v2.13.0/gh_2.13.0_linux_amd64.tar.gz
          tar -zxvf gh_2.13.0_linux_amd64.tar.gz
          chmod +x gh_2.13.0_linux_amd64/bin/gh
          cp gh_2.13.0_linux_amd64/bin/gh /bin

      - name: open PR at outbreak-detection
        run: |
          echo ${{ secrets.GH_API_TOKEN }} | gh auth login --with-token
          gh repo clone lifebit-ai/nlp-outbreak-detection && cd nlp-outbreak-detection
          git switch -c geocoder/${GITHUB_REF##*/}
          git push https://${{ secrets.GH_USER_NAME }}:${{ secrets.GH_API_TOKEN }}}@github.com/lifebit-ai/nlp-outbreak-detection.git --set-upstream origin geocoder/${GITHUB_REF##*/}
          gh pr create --title "Update geocoder version" --body "Please update geocoder version"'
